# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1bc223f43e09b281486244b7c728fa4d38ad0e50cf6b8d4642dc58b1a3a4b5cf38fc18f13df2415e114c2f23213cfd34f0226521fc3a272041e4a5074cfa0d
  google_client_id: <%= Settings.googleplus[:google_client_id] %>
  google_client_secret: <%= Settings.googleplus[:google_client_secret] %>
  facebook_app_id: <%= Settings.facebook[:facebook_app_id] %>
  facebook_app_secret: <%= Settings.facebook[:facebook_app_secret] %>
  twitter_api_key: <%= Settings.twitter[:twitter_api_key] %>
  twitter_api_secret: <%= Settings.twitter[:twitter_api_secret] %>
  s3_region: <%= Settings.s3[:region] %>
  s3_access_key: <%= Settings.s3[:access_key] %>
  s3_secret_key: <%= Settings.s3[:secret_key] %>
  s3_bucket: <%= Settings.s3[:bucket] %>

test:
  secret_key_base: 73278d6dca94cd90bf205a9722c8b841d05f868dc89dd3692ccda7ce9f9da870f6e7b56f3c8499c1644a9d79c923ffefc26d465f35a784f20d65116340d4fc12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_access_key: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret_key: <%= ENV["S3_SECRET_KEY"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>